### ISSUE TITLE
référencement gh-pages

### ISSUE THREAD

**Issue by nicolasdb** [zuperninja/blog#11]
Comment augmenter la visibilité de son portfolio dans les moteurs de recherches?

pour aider j'ai trouvé ceci
https://help.github.com/articles/search-engine-optimization-for-github-pages/

**Comment by zuperninja** [comment]
Ca l'air pas mal le SEO déjà inclus dans le thème:

https://github.com/mmistakes/minimal-mistakes/issues/324#issuecomment-282479194

**Comment by nicolasdb** [comment]
cool, 
faudra un petit tuto pour mieux comprendre comment ça marche et où mettre à jour ce qu'il faut. :+1:
