### ISSUE TITLE
Tester des changements HTML/CSS

### ISSUE THREAD

**Issue by zuperninja** [zuperninja/blog#12]
## contexte

Je travaille que via le site web github pour mettre à jour mon site, et je test des trucs visuellement et explore les différentes techniques. Problème : je dois attendre entre chaque mise à jour pour voir ce qu'il se passe. Et ça fait plein de commit. C'est pas propre.

## objectif

Fixer ça.

## proposition

Passer par l'examinateur de firefox. Avant je ne l'utilisais que pour le CSS jusqu'à temps que je me rende compte que je pouvais faire pareil pour le html (clic droit > modifier comme html). Si ça me plait, je copie colle dans mon fichier.md

## resultats

Moins de commit
Gain de temps

**Comment by nicolasdb** [comment]
HoooooOOooooo. 
Par contre, je m'y retrouve pas dans l'html généré en rapport de mon .md. 

L'autre solution, c'est d'installer un serveur jekyll en local. Y a plein de tuto aussi en ligne, ils disent que c'est simple mais pfff, j'ai pas l'habitude de toutes ces notions de localhost and shit.

**Comment by zuperninja** [comment]
C'est surtout pour quand je rajoute du html pour des tableaux avec images ou des trucs plus complexe. Pour le markdown, le preview de github suffit :)

**Comment by nicolasdb** [comment]
haaa ok, je vais y jeter un oeil la prochaine fois
