### ISSUE TITLE
The Starius Project

### ISSUE THREAD

**Issue by zuperninja** [zuperninja/blog#4]
@ElectroGuyMika needed help to design and add some content to his website before the [Maker Faire Lille](https://lille.makerfaire.com/) event. (Where he wanted to introduce his new prototype.)

The website had to be simple: one landing page with a contact form. The goals were to boost his online presence, and to simplify the contact process for people interested in knowing more.
My job was to put the website together, in a short period of time and without much content. And of course, to create the documentation for him to be able to manage the website on his own.
Another challenge was to find the aesthetic he was looking for: [VaporWave](https://en.wikipedia.org/wiki/Vaporwave)! A led-based, retro and colourful light painting can-thingy. The design of the website had to match the product. The challenge was to provide a smooth and efficient yet 60-70s inspired, nostalgic and neon-friendly website. 

## Process: 

I sent him about a dozen questions. Like these:

> What is your pitch? What do you expect from your website? How are you?

I started to work on the design before having any content. Not ideal, because you can easily get lost, and end up doing things you don’t need. But with the short deadline it was a good choice. This way, when he sent me the content, I only had to delete what I didn’t need.
I took quite some time to research the right aesthetic. A journey through [neon lights](https://about-blank.co/wp-content/uploads/2016/06/simpsonwave.jpg) banners and [flashing images.](https://www.themebeta.com/files/picture/201609/22/708d8052c367f45a22b01b67c0874d03.gif) 

<iframe width="560" height="315" src="https://www.youtube.com/embed/UJsUpeXK6Jo?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

With the little bit of time I had left, I worked on the SEO and the graphics.

## Making it: 

One of his friends had already bought the domain name and installed [Wordpress](https://wordpress.org/) and the theme.
I spent 1.5 hours to discover and explore the theme (https://www.kadencethemes.com/product/pinnacle-free-theme/) and the visual builder ([SiteOrigin](https://siteorigin.com/page-builder/)). I highly recommend using them together. I noticed the builder might be slowing down the website, but I will research this issue during the second part of the mission.
I then added the plugin we needed, and uninstalled the useless ones. This way, it will be easier for @ElectroGuyMika to focus on updating his online content, without having to worry about the technical stuff.
I worked on a graphic chart to harmonize all of the future content, based on the artwork he gave me.
And yes, I really dig the pink neon colour!

![image](https://user-images.githubusercontent.com/25099826/36471722-156dc954-1722-11e8-96ac-a7b260080b8b.png)

## Resources: 
For the social media icons I used [FontAwesome](https://fontawesome.com/)
For creating the graphic content I used [Inkscape](https://inkscape.org)

## Next steps: 

- [ ] Add content 
- [ ] Speed up & optimize 
- [ ] Add new fonts 
- [ ] Ease in-out scroll 
- [ ] Publish gallery grid (waiting for the photo shoot) 
- [ ] Optimize responsive design
- [ ] Create tutorials for adding more content 
- [ ] Add a fav icon 

## WIP: 

Phase 1:  approx. 14 hours
Phase 2: coming soon
URL: http://thestariusproject.com/
Time report : [Toggl_time_entries.pdf](https://github.com/zuperninja/blog/files/1743706/Toggl_time_entries_2018-01-01_to_2018-12-31.pdf)

**Comment by zuperninja** [comment]
[Toggl_time_entries_2018-01-01_to_2018-12-31.pdf](https://github.com/zuperninja/blog/files/1743706/Toggl_time_entries_2018-01-01_to_2018-12-31.pdf)

**Comment by nicolasdb** [comment]
trop classe, 
j'aime bien la touche du rapport toggl. +1 transparance, +1 éthique :+1: 
Et ton label **hireling**, c'est les jobs?

**Comment by zuperninja** [comment]
Sur mon site je vais mettre une section hireling (mercenaire) et du coup ce projet est un job. Mais est-ce que c'est aussi une quête ? ou bien ca va dans portfolio ? est-ce que hireling et portfolio c'est la même chose ? who know ?! :D

**Comment by zuperninja** [comment]
Et pour toggl, j'aimerai que mon activité soit en freeprix. (du moins je vais tester d'abord). Donc d'avoir un détail de heures pour donner une meilleure idée de ce que j'ai fait pendant ce x nombre d'heure. Certains peuvent trouver que la documentation fait partie entière du job, et donc aussi financer ça. Ou bien d'autre vont penser que la prospection c'est du bullshit et que ça mérite pas d'etre payé. Ou bien que la tache que j'ai faite n'était pas dans le cahier des charges. Bref c'est pour donner une meilleure vision de où va l'argent et combien coûte mon travail

**Comment by nicolasdb** [comment]
Nice. cool d'essayer oui. :)

post, quest, tout ça.... 
Comme je vois les choses, un post c'est un sujet précis, une issue. Qui peut être soit autonome soit lié à une quest. 
Je gère ça dans mes tags, et la liste des posts est ajoutée suivant ces tags dans les quêtes correspondantes. 

Hireling, j'aime bien :+1: 
ça peut être une quest en soi, qui réunis tes différentes missions. 
#deadpool

**Comment by zuperninja** [comment]
Capture fait avec fireshot 

![image](https://user-images.githubusercontent.com/25099826/38072772-20dc93e6-3352-11e8-85db-fa21ba05295a.png)

**Comment by zuperninja** [comment]
![screenshot_stariusproject](https://user-images.githubusercontent.com/25099826/38077047-c17c963e-3361-11e8-84b1-4ad7c67604e4.png)
