### ISSUE TITLE
comment annoncer graphiquement le changement de langue - site bilingue

### ISSUE THREAD

**Issue by zuperninja** [zuperninja/blog#6]
🇫🇷 
🇬🇧

**Comment by nicolasdb** [comment]
tu pense à quoi comme plateforme ? actuellement, su rgh-pages, j'ai pas encore trouvé comment gérer les langues.
J'ajoute simplement un tag FR ou EN pour trier.

**Comment by zuperninja** [comment]
ma home page su rle bog est bilingue, fr et en mélangé, c'est pas très
pratique, je vais essayer aec des icones je pense

Le 4 mars 2018 à 19:51, Nicolas de Barquin <notifications@github.com> a
écrit :

**Comment by zuperninja** [comment]
https://github.com/lipis/flag-icon-css

**Comment by zuperninja** [comment]
http://www.famfamfam.com/lab/icons/flags/

**Comment by zuperninja** [comment]
![icons8_france_40px](https://user-images.githubusercontent.com/25099826/38572244-e109f63c-3cf2-11e8-9697-08deca69cc9c.png)
![icons8_great_britain_40px](https://user-images.githubusercontent.com/25099826/38572268-f4afff88-3cf2-11e8-9b0b-ecb238b684b0.png)

**Comment by zuperninja** [comment]
Code à mettre endessous du YAML en début de post:

`
[FR]:https://user-images.githubusercontent.com/25099826/38572363-383b1b2a-3cf3-11e8-9c2c-47626e7eb523.png
[EN]:https://user-images.githubusercontent.com/25099826/38572348-2adf455a-3cf3-11e8-8b14-a0ef13f9c261.png`
