### ISSUE TITLE
Ink and Earth

### ISSUE THREAD

**Issue by zuperninja** [zuperninja/blog#9]
https://answers.squarespace.com/questions/13008/folder-navigation%3A-top-folder-doesnt-link-to-anything%2C-can-i-get-it-to-or-remove-link-behavior.html

https://answers.squarespace.com/questions/24095/how-can-i-change-the-logo-link-destination-to-another-page-on-my-site.html

**Comment by zuperninja** [comment]
2hours : talk teaching
5hours : helping+technical stuff

**Comment by zuperninja** [comment]
Issue : lightbox
- without caption beside the picture (only overlay) 
- hide the logo (https://answers.squarespace.com/questions/178347/wexely-hiding-page-header-in-lightbox.html?childToView=178349#comment-178349)

**Comment by zuperninja** [comment]
Squarespace : 
| Pro | Con |
|---|---|
|easy to use and to update|hard to know wich templates as the option you need|
|beautiful design|cannot reused a picture you already use withou upload it again|

**Comment by zuperninja** [comment]
try with flatiron : 

https://answers.squarespace.com/questions/23791/flatiron-is-it-possible-to-make-a-dropdown-menu-of-index-pages.html

https://answers.squarespace.com/questions/90839/how-can-i-move-my-flatiron-navigation-to-the-right-side.html

**Comment by zuperninja** [comment]
#navigator header#topBar ul#nav {
       float: right;
       padding: 100px 0 15px 0 ;}

#navigator footer#bottomBar #footerBlock p { 
margin: 0;
padding: 0;
}

**Comment by zuperninja** [comment]
a:hover {
  border:none !important;
  text-decoration:none !important;
}

a {
  border:none !important;
  text-decoration:none !important;
}

**Comment by zuperninja** [comment]
- [ ]  remplace social icon by fontawesome (blocked by adblock)
- [ ] upload pictures
- [ ] margin top header too big ?
- [ ] comment the custom css when done

**Comment by zuperninja** [comment]
# Ink and Earth: Coaching, teaching and tweaking CSS

Ink and Earth needed a website to showcase her work in illustration. She already have a great funnel for her skinart through Instagram and Facebook. The next step was to build a website for reaching a more professionnal oriented audience.


The challenge was to find a simple platform to use for her to upload her work through her tablet, with a good SEO and a professional look. She wants to reach a new public to optimize her prospection. 

It was a great pleasure to work with Ink and Earth on her website. First because she is my jungle neighbor, and second because her artwork is amazing.

## Process: 

I heard a lot of good things about Squarespace from creative no-nerd people.

**Comment by zuperninja** [comment]
![image](https://user-images.githubusercontent.com/25099826/38075391-6927e434-335c-11e8-8343-51e6f77db5a2.png)

**Comment by nicolasdb** [comment]
J'ai vu que t'as tenté un tableau plus haut, non? 

Attention aux " | " ça doit bien être régulier entre les colonnes. 
L'astuce, c'est de copier/coller un tableau simple d'un tableur office ou google. 
github te le converti direct comme il faut dans ton issue.

**Comment by zuperninja** [comment]
Pro | Con
-- | --
easy to use and to update | hard to know wich templates as the option you need
beautiful design | cannot reused a picture you already use withou upload it again

**Comment by zuperninja** [comment]
WHAT THE ACTUAL FUCK ! THAT'S MAGIC !! Merci !!! ça va me faire gagner un temps de fouuuuuu !

**Comment by nicolasdb** [comment]
github, il est trop fort.
